apiVersion: apps/v1
kind: Deployment
metadata:
  name: casino-frontend
  labels:
    app: casino-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: casino-frontend
  template:
    metadata:
      labels:
        app: casino-frontend
    spec:
      containers:
        - name: frontend
          image: 403943113547.dkr.ecr.us-east-1.amazonaws.com/casino-frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /livez
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: casino-frontend-service
spec:
  type: LoadBalancer 
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: casino-frontend